### ISSUE TITLE
Installation / 404

### ISSUE THREAD

**Issue by foorb** [nebulade/guacamoly#42]
Hey,

your demo looks great so far, I really like it. 
I installed the app as you described:
```
cd guacamoly
npm i
./app.js
```
Also added a user:
`./admin user-add --username test --password test --display-name "Test User"`

An starting it:
`APP_ORIGIN="http://domain.tld" LOCAL_AUTH_FILE=".users.json" node app.js`

But I'm getting the error:
```
App listening at http://:::3000
GET / 404 10.170 ms - 13
GET /favicon.ico 404 2.104 ms - 24
```

any idea?

**Comment by nebulade** [comment]
My bad, I forgot to mention that one also has to run `gulp` to build the actual website assets.
