### ISSUE TITLE
Minimal MongoDB version

### ISSUE THREAD

**Issue by foorb** [nebulade/guacamoly#44]
Hi,
Can you please specify the required MongoDB version?
I think it must be >2.6, else you getting the following error when using the search.

```
name:          HttpError
status:        500
message:       Internal error
internalError:
  """
    name:    MongoError
    message: invalid operator: $search
    stack:
      """
        MongoError: invalid operator: $search

```
http://stackoverflow.com/questions/23213007/mongo-db-error-invalid-operator-search-when-doing-text-search

**Comment by nebulade** [comment]
I don't actually know the minimal required version. The Cloudron [addon](https://cloudron.io/references/addons.html#mongodb) is v2.6.3 and this is what I test against mostly. So looks like your observation is correct with >2.6
